/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContentWrap: typeof import('./../components/ContentWrap/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ErrorBoundary: typeof import('./../components/ErrorBoundary/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    InfiniteScroll: typeof import('./../components/InfiniteScroll/index.vue')['default']
    LazyChart: typeof import('./../components/LazyChart.vue')['default']
    OptimizedImage: typeof import('./../components/OptimizedImage/OptimizedImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./../components/Skeleton/index.vue')['default']
    Table: typeof import('./../components/Table/index.vue')['default']
    VirtualList: typeof import('./../components/VirtualList/index.vue')['default']
  }
}
